name: Тестирование и поставка

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  server_update:
    runs-on: ubuntu-latest
    steps:
    - name: Доставка изменений
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /opt/app/cicd
          bash ./update.sh